### ISSUE TITLE
"Error in SteamVR connection"

### ISSUE THREAD

**Issue by Moosiee** [ju1ce/Mediapipe-VR-Fullbody-Tracking#6]
Terminal says, 
"Importing libraries....
Reading parameters...
Opening camera...
Connecting to SteamVR
Error in SteamVR connection. Retrying...
Camera opened!
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Error in SteamVR connection. Retrying...
Could not connect to SteamVR after 10 retries!"

I have very little technical experience, sorry for the vague description.

**Comment by ju1ce** [comment]
This usualy happens if the driver is not installed correctly, or isnt enabled.

Did the install_driver.exe from /driver_files install the driver properly, or did it crash/give an error? It should finish by telling you it has successfuly installed the driver.

If yes, check steamvr settings -> startup -> addons. Apriltagtrackers should be listed there, make sure it is enabled.

If it is not on the list, driver has failed to load. In that case, you should check vrserver.txt file inside steam/logs and search for apriltagtrackers. If it doesnt find anything, the driver isnt installed, and you shoud try to install the driver manualy: simply copy the apriltagtrackers folder from /driver files and paste it into steam/steamapps/common/steamvr/drivers. If it found anything, it should give you a hint at whats wrong, or you can also paste the relavant parts of the file here for me to look at.

**Comment by Moosiee** [comment]
What ended up fixing it was redownloading SteamVR. Thank you for the quick response!
